server:
  host: "127.0.0.1"
  port: 3000

database:
  pool_size: 10

jwt:
  expiration_minutes: 60

smtp:
  from: "noreply noreply@example.com"
  host: "smtp.example.com"

app:
  verification_url: "http://localhost/verify"